public class ApexConstantsCls { 
        public static final INTEGER DEFAULT_SIZE= 3; 
        public static final STRING INITIAL_SUBMIT= 'Draft';
        public static final STRING ERROR_MESSAGE = 'An error has occurred, please contact Admin.';
    
    	
	public static final String RELATIONSHIP_P = 'Product';
	public static final String RELATIONSHIP_PS = 'Product and Services';
	public static final String RELATIONSHIP_S = 'Services';
	public static final String TYPE_OTHER = 'Other Services';
	public static final String STATUS_ACTIVE = 'Active';
	public static final String STATUS_INACTIVE = 'Inactive';
	public static final String PAGE_BANNER_NEWS = 'Page Banner News';
	public static final String TOP_BANNER_NEWS = 'Top Banner News';
	public static final String DEFAULT_VALUE = 'Default';
	public static final String APPROVER_VALUE = 'Approver';
	public static final String YES_VALUE = 'Yes';
	public static final String COUNTRY_GLOBAL = 'Global';
	public static final String PRODUCT_CONTENT_NCT = 'NCT';
	public static final String PRODUCT_ACCESS_MDT_HELP_DESK = 'Help Desk';
	

	/******* CASE STATUS ****/
	public static final String STATUS_PENDING = 'Pending Approval';
	public static final String STATUS_APPROVED = 'Approved';
	public static final String STATUS_REJECTED = 'Rejected';
	public static final String STATUS_CLOSED = 'Closed';
	/******* END CASE STATUS ****/

	/******* ACCESS TYPES  ****/
    public static final String TYPE_tileAccessSWUC = 'SWUC'; //NOKIASP-5063
	public static final String TYPE_CDB = 'CDB';
	public static final String TYPE_CARES = 'CARES';
	public static final String PIC_VALUE = 'PIC';
	public static final String HD_VALUE = 'Help Desk';
	//public static final String SMC_VALUE = 'Software Maintenance Collaboration (SWM)';
	public static final String NCT_VALUE = 'NCT';
	public static final String NCP_chACCESS_TYPE = 'CH';
	public static final String NCP_chhwsACCESS_TYPE = 'CHHWS';
	public static final String MANAGE_SUPPORT = 'ManageSupport';
	/******* END ACCESS TYPES ****/

	public static final String SUCCESS_VALUE = 'Success';
	public static final String BUSINESS_HOUR_NCP = 'Support Portal';
	public static final String PARTNER_PORTAL_ACCESS_TYPE = 'Partner Portal';
	public static final String USER_NCP_RELATIONS_PARTNER = 'Partner';
	public static final String SUPPLIER_PORTAL_ACCESS_TYPE = 'Supply Chain Portal';
	public static final String USER_NCP_RELATIONS_SUPPLIER = 'Supplier';
	
	
	

	/******* SERVICE CONTRACT  ****/
	public static final String SERVICE_CONTRACT_RT_DEVNAME_PARENT = 'NCP_Parent_Service_Contract';
	public static final String SERVICE_CONTRACT_RT_DEVNAME_CHILD = 'NCP_Child_Service_Contract';
	public static final String SERVICE_CONTRACT_RT_DEVNAME_OTHER = 'Other_Services_Child_Service_Contract';
	/******* END SERVICE CONTRACT  ****/

	/******* CASE  ****/
	public static final String CASE_RT_DEVNAME_ENTITLEMENT = 'NCP_Upgrade_Customer_Entitlements';
	public static final String CASE_SUBJECT = 'Upgrade Services Request';
	public static final String CASE_PRIORITY = 'Medium';
	/******* END CASE  ****/

	/******* EMAIL TEMPLATE  ****/
	public static final String EMAIL_TEMPLATE_TEAM = 'NCP_Case_creation_for_Case_team';
	public static final String EMAIL_TEMPLATE_KEYUSER = 'NCP_Case_creation_for_KeyUser';
	public static final String EMAIL_TEMPLATE_INTERNAL = 'NCP_Internal_Case_creation';
	public static final String EMAIL_TEMPLATE_SW_INTEGRATOR_EMAIL = 'NCP_SW_IntegratorEmail';
	/******* END EMAIL TEMPLATE  ****/

	/******* PROFILES  ****/
	public static final String PROFILE_LOGIN_CUSTOMERS = 'Customers Login';
	public static final String PROFILE_CUSTOMERS = 'Customers';
	public static final String PROFILE_CUSTOMER_COMMUNITY_PLUS = 'Customer Community Plus User';
	public static final String PROFILE_LOGIN_CUSTOMER_COMMUNITY_PLUS = 'Customer Community Plus Login User';
	/******* END PROFILES  ****/

	/******* Account ****/
	public static final String BUSINESS_PARTNER_ROLE = 'SW Integrator';
	public static final String ACCOUNT_RT_DEVNAME_CUSTOMER = 'Customer';
	public static final String ACCOUNT_RT_DEVNAME_LEGALENTITY = 'Legal_Entity';
	/******* End Account ***/

	/******* PRODUCT LIST VIEWs  ****/
	public static final String FAVORITE_PRODUCTS_LIST_VIEW = 'Favorite Products';
	public static final String MY_ENTITLED_LIST_VIEW = 'My Entitled Products';
	public static final String ALL_SERVICES_LIST_VIEW = 'All Services Products';
	/******* END LIST VIEWs  ****/

	/******** APEX Sharing  ****/
	public static final String RAW_CAUSE_OWNER = 'Owner';
	public static final String RAW_CAUSE_MANUAL = 'Manual';
	public static final String ACCESS_LEVEL_READ = 'Read';
	/******** END APEX Sharing  ****/
	
	/******** Custom Metadata  ****/
	public static final String MANAGESUPPORTTICKETS_LINK_QUALIFIEDAPINAME = 'TroubleshootingInformation_ManageSupport';
   /******** Custom Metadata  ****/
    }