public  class company {
 public string trainer='mohan';
    public company(){
        
    }
 
// Wrapper Class Construction
 
public class wrapper{
 
public String Tname{get;set;}
public String Tcity{get;set;}
public String Dcountry{get;set;}
public String Dphone{get;set;}
// Wrapper class constructor
 
public wrapper(String Tname,String Tcity,String Dcountry,String Dphone){
this.Tname=Tname;
this.Tcity=Tcity;
this.Dcountry=Dcountry;
this.Dphone=Dphone;
}
 
}

}